/*****************************************************************************
    NumeRe: Framework fuer Numerische Rechnungen
    Copyright (C) 2014  Erik Haenel et al.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
******************************************************************************/


#ifndef ERROR_HPP
#define ERROR_HPP

#include <string>
using namespace std;

extern string sErrorToken;
extern int nErrorIndices[2];

enum errorcode
{
    STRING_ERROR,
    PROCEDURE_THROW,
    LOOP_THROW,
    TOO_MANY_ARGS,
    MISSING_DEFAULT_VALUE,
    WRONG_ARG_NAME,
    INVALID_PROCEDURE_NAME,
    FILE_NOT_EXIST,
    CANNOT_OPEN_TARGET,
    CANNOT_OPEN_SOURCE,
    PROCEDURE_NOT_FOUND,
    UNMATCHED_PARENTHESIS,
    PROCEDURE_ERROR,
    INVALID_DATA_ACCESS,
    NO_DATA_AVAILABLE,
    READ_ONLY_DATA,
    NO_CACHED_DATA,
    NO_MATRIX,
    INVALID_INDEX,
    INVALID_ELEMENT,
    CANNOT_CONTAIN_STRINGS,
    FUNCTION_ERROR,
    SEPARATOR_NOT_FOUND,
    NO_DIFF_VAR,
    NO_DIFF_OPTIONS,
    DIFF_VAR_NOT_FOUND,
    NO_EXTREMA_VAR,
    NO_EXTREMA_OPTIONS,
    EXTREMA_VAR_NOT_FOUND,
    NO_ZEROES_VAR,
    NO_ZEROES_OPTIONS,
    ZEROES_VAR_NOT_FOUND,
    NO_EVAL_VAR,
    NO_EVAL_OPTIONS,
    EVAL_VAR_NOT_FOUND,
    CANNOT_PLOT_STRINGS,
    WRONG_PLOT_INTERVAL_FOR_LOGSCALE,
    TOO_FEW_COLS,
    TOO_FEW_LINES,
    CANNOT_FIND_DEFINE_OPRT,
    FUNCTION_ALREADY_EXISTS,
    FUNCTION_IS_PREDEFINED,
    FUNCTION_STRING_IS_COMMAND,
    CANNOT_FIND_FUNCTION_ARGS,
    NO_NUMBER_AT_POS_1,
    FUNCTION_NAMES_MUST_NOT_CONTAIN_SIGN,
    TOO_MANY_ARGS_FOR_DEFINE,
    INCOMPLETE_VECTOR_SYNTAX,
    ELLIPSIS_MUST_BE_LAST_ARG,
    TOO_MANY_VECTORS,
    TOO_MANY_FUNCTION_CALLS,
    CANNOT_SAVE_CACHE,
    CANNOT_SAVE_FILE,
    SCRIPT_NOT_EXIST,
    CANNOT_SORT_DATA,
    CANNOT_SORT_CACHE,
    CANNOT_SMOOTH_CACHE,
    CANNOT_RETOQUE_CACHE,
    CANNOT_RESAMPLE_CACHE,
    CANNOT_MOVE_DATA,
    CANNOT_MOVE_FILE,
    CANNOT_REMOVE_FILE,
    CANNOT_DELETE_ELEMENTS,
    CANNOT_COPY_DATA,
    CANNOT_COPY_FILE,
    CANNOT_EXPORT_DATA,
    NO_FILENAME,
    DATAFILE_NOT_EXIST,
    CANNOT_READ_FILE,
    FUNCTION_CANNOT_BE_FITTED,
    NO_FUNCTION_FOR_FIT,
    NO_PARAMS_FOR_FIT,
    NO_DATA_FOR_FIT,
    FITFUNC_NOT_CONTAINS,
    CANNOT_BE_A_FITTING_PARAM,
    CANNOT_GENERATE_DIRECTORY,
    CANNOT_GENERATE_SCRIPT,
    CANNOT_GENERATE_PROCEDURE,
    CANNOT_GENERATE_FILE,
    IF_OR_LOOP_SEEMS_NOT_TO_BE_CLOSED,
    CANNOT_EDIT_FILE_TYPE,
    NO_INTEGRATION_RANGES,
    INVALID_INTEGRATION_PRECISION,
    NO_INTEGRATION_FUNCTION,
    INVALID_INTEGRATION_RANGES,
    NO_COLS,
    NO_ROWS,
    UNKNOWN_PATH_TOKEN,
    INVALID_FILETYPE,
    COL_COUNTS_DOESNT_MATCH,
    CANNOT_EVAL_IF,
    CANNOT_EVAL_FOR,
    CANNOT_EVAL_WHILE,
    NO_TARGET,
    EXTERNAL_PROGRAM_NOT_FOUND,
    NUMBER_OF_FUNCTIONS_NOT_MATCHING,
    PROCEDURE_WITHOUT_INSTALL_FOUND,
    INSTALL_CMD_FOUND,
    CANNOT_OPEN_LOGFILE,
    CANNOT_OPEN_FITLOG,
    PLUGINCMD_ALREADY_EXISTS,
    PLUGINNAME_ALREADY_EXISTS,
    PLUGIN_HAS_NO_CMD,
    PLUGIN_HAS_NO_MAIN,
    PLUGIN_MAY_NOT_OVERRIDE,
    FILETYPE_MAY_NOT_BE_WRITTEN,
    NO_STRING_FOR_WRITING,
    INVALID_HLPIDX,
    HLP_FILE_MISSING,
    PLOTDATA_IS_NAN,
    HLPIDX_ENTRY_IS_MISSING,
    OVERFITTING_ERROR,
    DATAPOINTS_CANNOT_BE_MODIFIED_WHILE_PLOTTING,
    TOO_LARGE_BINWIDTH,
    TOO_FEW_ARGS,
    TOO_FEW_DATAPOINTS,
    TOO_LARGE_CACHE,
    TABLE_DOESNT_EXIST,
    STRINGVARS_MUSTNT_BEGIN_WITH_A_NUMBER,
    STRINGVARS_MUSTNT_CONTAIN,
    FILE_IS_EMPTY,
    CANNOT_RELOAD_DATA,
    PLOT_ERROR,
    INVALID_CACHE_NAME,
    CACHE_ALREADY_EXISTS,
    CACHE_DOESNT_EXIST,
    CACHE_CANNOT_BE_RENAMED,
    PRIVATE_PROCEDURE_CALLED,
    INLINE_PROCEDURE_IS_NOT_INLINE,
    INVALID_INTERVAL,
    NO_MATRIX_FOR_MATOP,
    WRONG_MATRIX_DIMENSIONS_FOR_MATOP,
    MATRIX_IS_NOT_INVERTIBLE,
    MATRIX_IS_NOT_SYMMETRIC,
    LGS_HAS_NO_SOLUTION,
    LGS_HAS_NO_UNIQUE_SOLUTION,
    NO_INTERVAL_FOR_ODE,
    NO_EXPRESSION_FOR_ODE,
    NO_OPTIONS_FOR_ODE,
    STRINGS_MAY_NOT_BE_EVALUATED_WITH_CMD,
    PROCESS_ABORTED_BY_USER
};


#endif // ERROR_HPP

